language: android
os: linux
dist: xenial

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.6

env:
  global:
    - CLOUD_PROJECT_ID=opencamera-extended
    - APP_PATH="$TRAVIS_BUILD_DIR/app/build/outputs/apk/release/app-release.apk"
    - TEST_APP_PATH="$TRAVIS_BUILD_DIR/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk"
    - TEST_TARGET="class net.sourceforge.opencamera.test.SubsetTests"

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - openssl aes-256-cbc -K $encrypted_9e5ce9a0670f_key -iv $encrypted_9e5ce9a0670f_iv -in opencamera-extended-firebase-adminsdk-yv5yz-e33a8ce5c1.json.enc -out ./opencamera-extended-firebase-adminsdk-yv5yz-e33a8ce5c1.json -d
  - openssl aes-256-cbc -K $encrypted_cec398169802_key -iv $encrypted_cec398169802_iv -in my-release-key.keystore.enc -out ./my-release-key.keystore -d
  - yes | sdkmanager "platforms;android-28"
  - curl -L https://packagecloud.io/github/git-lfs/gpgkey | sudo apt-key add -

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

before_script:
  - python3 --version
  - export CLOUDSDK_PYTHON=$(which python3.6)
  - gcloud version || true
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud components update
  - gcloud version
  - echo $CLOUD_PROJECT_ID
  - gcloud auth activate-service-account --key-file ./opencamera-extended-firebase-adminsdk-yv5yz-e33a8ce5c1.json
  - gcloud config set project $CLOUD_PROJECT_ID

script: 
  - ./gradlew assembleRelease
  - ./gradlew assembleDebug
  - ./gradlew assembleAndroidTest
  - ./gradlew test
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"[run instrumentation]"* ]]; then
      travis_wait gcloud firebase test android run --type instrumentation
       --app $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
       --test $TRAVIS_BUILD_DIR/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
       --device model=blueline,version=28,locale=en,orientation=portrait
       --device model=x1q,version=29,locale=en,orientation=portrait
       --test-targets "class net.sourceforge.opencamera.test.SubsetTests";
    fi

deploy:
  skip-cleanup: true
  provider: releases
  api-key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/app-release.apk
  name: $TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: false
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true
