language: android
os: linux
dist: xenial

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - android-25
    - sys-img-armeabi-v7a-android-25
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"

before_script:
# Launch emulator before the execution
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -debug -logcat -camera-back emulated &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script: ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=net.sourceforge.opencamera.test.VideoNoSafTests --info

