language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
  licenses:
    - 'androidx_LICENSE-2.0'
    - 'google_material_design_icons_LICENSE-2.0'

before_install:
  - yes | sdkmanager "platforms;android-28"

script: ./gradlew build
