language: android
os: linux
dist: xenial

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - openssl aes-256-cbc -K $encrypted_9e5ce9a0670f_key -iv $encrypted_9e5ce9a0670f_iv -in opencamera-extended-firebase-adminsdk-yv5yz-e33a8ce5c1.json.enc -out ./opencamera-extended-firebase-adminsdk-yv5yz-e33a8ce5c1.json -d
  - openssl aes-256-cbc -K $encrypted_cec398169802_key -iv $encrypted_cec398169802_iv -in my-release-key.keystore.enc -out ./my-release-key.keystore -d
  - yes | sdkmanager "platforms;android-28"

script: 
  - ./gradlew assembleRelease
  - ./gradlew assembleDebug

deploy:
  skip-cleanup: true
  provider: releases
  api-key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/release/app-release.apk
  name: dev-build-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true
