name: Emulator test run

on:
  push:
    branches: 
      - emulator_tests
  workflow_dispatch:
jobs:
    EMULATOR_TEST:
        name: Emulator test
        runs-on: macos-latest
        strategy:
          fail-fast: false
          matrix:
            EMULATOR_API: [22, 23, 24, 25, 26, 27, 28]
            include:
              - EMULATOR_API: 28
                EMULATOR_ARCH: x86_64
              - EMULATOR_API: 27
                EMULATOR_ARCH: x86_64
              - EMULATOR_API: 26
                EMULATOR_ARCH: x86_64
              - EMULATOR_API: 25
                EMULATOR_ARCH: x86
              - EMULATOR_API: 24
                EMULATOR_ARCH: x86
              - EMULATOR_API: 23
                EMULATOR_ARCH: x86
              - EMULATOR_API: 22
                EMULATOR_ARCH: x86
        steps:
          - uses: actions/checkout@v2

          - uses: gradle/wrapper-validation-action@v1

          - uses: actions/setup-java@v1
            with:
              java-version: 15

          - name: Android Emulator Runner
            # You may pin to the exact commit or the version.
            uses: ReactiveCircus/android-emulator-runner@4a8a9af74c6a180bc5fcf80852847a0ea62fecb3
            # uses: ReactiveCircus/android-emulator-runner@v2.11.0
            with:
              # API level of the platform and system image - e.g. 23 for Android Marshmallow, 29 for Android 10
              api-level: ${{ matrix.EMULATOR_API }}
              arch: ${{ matrix.EMULATOR_ARCH }}
              disable-animations: true
              profile: Nexus 5X
              working-directory: ./
              emulator-options: -no-snapshot -no-window -no-boot-anim -gpu swiftshader_indirect -camera-back emulated -camera-front emulated
              script: ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=net.sourceforge.opencamera.test.VideoNoSafTests --info
              # custom script to run - e.g. `./gradlew connectedCheck`
