name: Emulator test run

on:
  push:
    branches: 
      - sensor_info
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Android Emulator Runner
        # You may pin to the exact commit or the version.
        # uses: ReactiveCircus/android-emulator-runner@4a8a9af74c6a180bc5fcf80852847a0ea62fecb3
        uses: ReactiveCircus/android-emulator-runner@v2.11.0
        with:
          # API level of the platform and system image - e.g. 23 for Android Marshmallow, 29 for Android 10
          api-level: 28
          script: ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=net.sourceforge.opencamera.test.VideoNoSafTests --info
