name: Run unit tests

on: [push, workflow_dispatch]

env:
  keystore_password: ${{ secrets.KeystorePassword }}
  keystore_alias: ${{ secrets.KeystoreAlias }}
  keystore_alias_password: ${{ secrets.KeystoreAliasPassword }}

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decrypt release key
        env:
          enc_key: ${{ secrets.KeystoreEncKey }}
          enc_iv: ${{ secrets.KeystoreEncIv }}
        run: openssl aes-256-cbc -d -K $enc_key -iv $enc_iv -in my-release-key.keystore.enc -out ./my-release-key.keystore

      - name: Assemble debug
        run: ./gradlew assembleDebug

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Test debug
        run: ./gradlew testDebugUnitTest

      - name: Test release
        run: ./gradlew testReleaseUnitTest

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
